package sadefaultgen.test4;

/* Default implementation of test4.AbstractTest5. Generated by Sureassert UC */

public class AbstractTest5 extends test4.AbstractTest5 {


public java.util.Set abstractMethod2(java.util.Set arg0)  { return null; }
public java.util.Set abstractMethod(java.util.Set arg0)  { return null; }

}