package sadefaultgen.test4;

/* Default implementation of test4.TestIF5. Generated by Sureassert UC */

public class TestIF5 implements test4.TestIF5 {


public java.util.List returnAT2()  { return null; }
public java.util.List returnAT()  { return null; }

}